default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: localhost
  username: postgres
  password: password
  database: development_rails

test:
  <<: *default
  host: localhost
  username: postgres
  password: password
  database: test_rails

production:
  <<: *default
  host: ec2-79-125-117-53.eu-west-1.compute.amazonaws.com
  port: 5432
  database: dfq280hjhpcoeg
  username: cxmtlvqadihojr
  password: 1145d98814dc00626f469b70c9b6a835375e171d6e55e73c3d482c810d8ee5cf
